language: node_js
node_js:
  - 0.12
#  - 0.12
#  - 0.11

branches:
  only:
    - master

cache:
  - codeclimate-test-reporter
  - grunt-cli
  - bower
  - firebase-tools
  - karma-cli

sudo: required

before_install:
  #Code Climate coverage
  - npm install -g codeclimate-test-reporter grunt-cli bower firebase-tools karma-cli

install:
  - cd angularclient
  - npm install
  - bower install
  - grunt build
 #- travis will do 'npm test' at this point and that will call
 #  our karma tests to be exec in phantomjs

script:
  - test $TRAVIS_PULL_REQUEST == "false"
  - echo "${TRAVIS_PULL_REQUEST}"
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master"
  - echo "${TRAVIS_PULL_REQUEST}"

#CI with firebase https://johnheroy.com/2014/10/17/continuous-firebase-deployment-with-travis.html
after_success:
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sbt publish
#  - mkdir /home/travis/tmp
#  - echo "${TRAVIS_PULL_REQUEST}"
  #- firebase deploy