language: node_js

node_js:
  - 0.12

#This means that only PRs and the master branch will be tested.
branches:
  except:
    - /-job-\d+/
  only:
    - master

#Environment Variables
env: CODECLIMATE_REPO_TOKEN=714d1312eddbb4b263501face4ca8dc2baa50c882abe5f606dc8c773e50257f8

#Code climate reporting for Travis build, This does not work for some reason, solved with env vars
#addons:
#  code_climate:
#    repo_token:714d1312eddbb4b263501face4ca8dc2baa50c882abe5f606dc8c773e50257f8

#Caching resources to speed up the process
cache:
  - codeclimate-test-reporter
  - grunt-cli
  - bower
  - firebase-tools
  - karma-cli

#Optional
#sudo: required

#Install dependencies for Travis build
before_install:
  - npm install -g codeclimate-test-reporter grunt-cli bower firebase-tools karma-cli
  - cd angularclient
  - npm install
  - bower install

install: npm test
 #- travis will do 'npm test' even if we don't declare it
 #  at this point and that will call
 #  our karma tests to be exec in phantomjs

before_script:
   - grunt build
   - echo "${TRAVIS_PULL_REQUEST}"
   - echo "${TRAVIS_BRANCH}"

script:
  - firebase --silent

#Code climate report coverage
after_script:
  - codeclimate < ./coverage/**/lcov.info

#CI with firebase https://johnheroy.com/2014/10/17/continuous-firebase-deployment-with-travis.html
after_success:
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then echo -e "not deployed since it's not a PR" | firebase deploy; fi
#  - mkdir /home/travis/tmp
#  - echo "${TRAVIS_PULL_REQUEST}"
  #- firebase deploy