language: node_js

node_js:
  - 0.12

#branches:
#  only:
#    - master

#Code climate reporting for Travis build
addons:
  code_climate:
    repo_token:714d1312eddbb4b263501face4ca8dc2baa50c882abe5f606dc8c773e50257f8

#Caching resources to speed up the process
cache:
  - codeclimate-test-reporter
  - grunt-cli
  - bower
  - firebase-tools
  - karma-cli

#Optional
#sudo: required

#Install dependencies for Travis build
before_install:
  - npm install -g codeclimate-test-reporter grunt-cli bower firebase-tools karma-cli
  - cd angularclient
  - npm install
  - bower install

install: true
 #- travis will do 'npm test' at this point and that will call
 #  our karma tests to be exec in phantomjs

before_script:
   - grunt build
   - echo "${TRAVIS_PULL_REQUEST}"
   - echo "${TRAVIS_BRANCH}"

script:
  - test $TRAVIS_PULL_REQUEST == "false"
  - echo "${TRAVIS_PULL_REQUEST}"
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master"
  - echo "${TRAVIS_PULL_REQUEST}"
  - echo "${TRAVIS_BRANCH}"

#CI with firebase https://johnheroy.com/2014/10/17/continuous-firebase-deployment-with-travis.html
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master"
#  - mkdir /home/travis/tmp
#  - echo "${TRAVIS_PULL_REQUEST}"
  #- firebase deploy