language: node_js
node_js:
  - 0.10
#  - 0.12
#  - 0.11

cache:
  - codeclimate-test-reporter
  - grunt-cli
  - bower
  - firebase-tools
  - yo
  - karma-cli
  - generator-karma
  - generator-angular

sudo: required

#  env:
#    global:
#    - RUBYOPT='-W0'
#    - COVERAGE=1

before_install:
  #Nodejs
  - sudo apt-get install nodejs
  #Npm
  - sudo apt-get install npm
  #Code Climate coverage
  - sudo npm install -g codeclimate-test-reporter
  #Grunt
  - sudo npm install -g grunt-cli
  #Bower
  - sudo npm install -g bower
  #Firebase Tools
  - sudo npm install -g firebase-tools
  #Yeoman
  - sudo npm install -g yo generator-karma generator-angular
  #Karma
  - sudo npm install -g karma-cli

install:
  - cd angularclient
  - karma start

#:_( Nasty issue that i don't like, i will think what to do with this
#and prepare travis to test ONLY angular, because it seems he it's not able to test
#the docker build, shame....
#https://github.com/travis-ci/travis-ci/issues/1196

#script: "sudo sh ./dockers/run_dockers.sh"

#install: sudo ./prerequisites_install.sh

#CI with firebase https://johnheroy.com/2014/10/17/continuous-firebase-deployment-with-travis.html
after_success:
  - mkdir /home/travis/tmp
#  - sudo $(which npm) install -g firebase-tools
#  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then echo -e "${FIREBASE_EMAIL}\n${FIREBASE_PASSWORD}" | firebase deploy; fi