nodeapi2:

 build: ../nodeapi2
 restart: always
 ports:
 - "8080:8080"
 links:
  - elasticsearch

kibana:

 build: ./kibana
 restart: always
 ports:
 - "5601:5601"
 links:
 - elasticsearch

elasticsearch:

 build: ./elasticsearch
 restart: always
 ports:
 - "9200:9200"
 - "9300:9300"
 volumes:
 - "/data:/data"

logstash:

 build: ./logstash
 restart: always
 ports:
 - "4545:4545"
 - "4546:4546"
