kibana:

 build: ./kibana

 restart: always
 ports:
 - "5601:5601"
 links:
 - elasticsearch

elasticsearch:

 build: ./elasticsearch
 restart: always
 ports:
 - "9200:9200"
 - "9300:9300"
 volumes:
 - "/data:/data"

logstash:

 build: ./logstash
 restart: always
 ports:
 - "4545:4545"
 - "4546:4546"

node_rss_api:

 build: ../node_rss_api
 restart: always
 ports:
 - "3000:3000"
 links:
  - elasticsearch
