#indentation is relevant!
nodeapi:

 build: ./nodeapi
 restart: always
 ports:
 - "8080:8080"

kibana:

 build: ./kibana2
 restart: always
 ports:
 - "5601:5601"
 links:
 - elasticsearch

elasticsearch:

 build: ./elasticsearch2
 restart: always
 ports:
 - "9200:9200"
 - "9300:9300"
 volumes:
 - "/data:/data"

logstash:

 build: ./logstash2
 restart: always
 ports:
 - "4545:4545"
 - "4546:4546"